# Album: http://imgur.com/a/24ByN
THOTH = [  "0 - The Fool { http://i.imgur.com/PQ2nG95.jpg }",
                "I - The Magus { http://i.imgur.com/qItZSaz.jpg }",
                "II - The Priestess { http://i.imgur.com/joRLHGK.jpg }",
                "III - The Empress { http://i.imgur.com/1xiJAUq.jpg }",
                "IV - The Emperor { http://i.imgur.com/yVKoH2j.jpg }",
                "V - The Hierophant { http://i.imgur.com/8q8wkZv.jpg }",
                "VI - The Lovers { http://i.imgur.com/7fBAtUv.jpg }",
                "VII - The Chariot { http://i.imgur.com/axTt8o6.jpg }",
                "VIII - Adjustment { http://i.imgur.com/jFK0rW9.jpg }",
                "IX - The Hermit { http://i.imgur.com/vKjpFv6.jpg }",
                "X - Fortune { http://i.imgur.com/SfcEUFi.jpg }",
                "XI - Lust { http://i.imgur.com/pybCauK.jpg }",
                "XII - The Hanged Man { http://i.imgur.com/NH0vt4j.jpg }",
                "XIII - Death { http://i.imgur.com/0RG898u.jpg }",
                "XIV - Art { http://i.imgur.com/G91EXFL.jpg }",
                "XV - The Devil { http://i.imgur.com/RnRASpz.jpg }",
                "XVI - The Tower { http://i.imgur.com/S6Z2f1f.jpg }",
                "XVII - The Star { http://i.imgur.com/3yYIGvm.jpg }",
                "XVIII - The Moon { http://i.imgur.com/wECfVYO.jpg }",
                "XIX - The Sun { http://i.imgur.com/NGwTuoK.jpg }",
                "XX - The Aeon { http://i.imgur.com/LhXJy0f.jpg }",
                "XXI - The Universe { http://i.imgur.com/HDwUWBF.jpg }",
                "Ace of Wands { http://i.imgur.com/UK2efBo.jpg }",
                "2 of Wands - Dominion { http://i.imgur.com/fbzFflB.jpg }",
                "3 of Wands - Virtue { http://i.imgur.com/DwU6See.jpg }",
                "4 of Wands - Completion { http://i.imgur.com/LiMx96X.jpg }",
                "5 of Wands - Strife { http://i.imgur.com/rPlrbyT.jpg }",
                "6 of Wands - Victory { http://i.imgur.com/YyB5fCr.jpg }",
                "7 of Wands - Valour { http://i.imgur.com/nE0HLRN.jpg }",
                "8 of Wands - Swiftness { http://i.imgur.com/ChFeclc.jpg }",
                "9 of Wands - Strength { http://i.imgur.com/wEod3NT.jpg }",
                "10 of Wands - Oppression { http://i.imgur.com/QipWoV0.jpg }",
                "Knight of Wands { http://i.imgur.com/sDVt9RW.jpg }",
                "Queen of Wands { http://i.imgur.com/cL17LkX.jpg }",
                "Prince of Wands { http://i.imgur.com/mB468fd.jpg }",
                "Princess of Wands { http://i.imgur.com/XMO3bNF.jpg }",
                "Ace of Cups { http://i.imgur.com/qm5f07V.jpg }",
                "2 of Cups - Love { http://i.imgur.com/AsweI48.jpg }",
                "3 of Cups - Abundance { http://i.imgur.com/wzQVmtq.jpg }",
                "4 of Cups - Luxury { http://i.imgur.com/ONZVO0P.jpg }",
                "5 of Cups - Disappointment { http://i.imgur.com/xvuIqvn.jpg }",
                "6 of Cups - Pleasure { http://i.imgur.com/Od1qfVh.jpg }",
                "7 of Cups - Debauch { http://i.imgur.com/h2F7eFh.jpg }",
                "8 of Cups - Indolence { http://i.imgur.com/PxdiTDy.jpg }",
                "9 of Cups - Happiness { http://i.imgur.com/JLGko7R.jpg }",
                "10 of Cups - Satiety { http://i.imgur.com/Wmm2lQL.jpg }",
                "Knight of Cups { http://i.imgur.com/rbQZuJ0.jpg }",
                "Queen of Cups { http://i.imgur.com/WdvOb9X.jpg }",
                "Prince of Cups { http://i.imgur.com/CqfClbW.jpg }",
                "Princess of Cups { http://i.imgur.com/BsgXCEO.jpg }",
                "Ace of Swords { http://i.imgur.com/nbGXZMt.jpg }",
                "2 of Swords - Peace { http://i.imgur.com/kpwBVKZ.jpg }",
                "3 of Swords - Sorrow { http://i.imgur.com/0z9d1hY.jpg }",
                "4 of Swords - Truce { http://i.imgur.com/9LNCSNC.jpg }",
                "5 of Swords - Defeat { http://i.imgur.com/Gub5DXA.jpg }",
                "6 of Swords - Science { http://i.imgur.com/etB8X8E.jpg }",
                "7 of Swords - Futility { http://i.imgur.com/gk1ivXT.jpg }",
                "8 of Swords - Interference { http://i.imgur.com/8eXSUQj.jpg }",
                "9 of Swords - Cruelty { http://i.imgur.com/eRQ4XX4.jpg }",
                "10 of Swords - Ruin { http://i.imgur.com/6E4h4d4.jpg }",
                "Knight of Swords { http://i.imgur.com/YZIa5um.jpg }",
                "Queen of Swords { http://i.imgur.com/hb0bjIQ.jpg }",
                "Prince of Swords { http://i.imgur.com/U8CHSV9.jpg }",
                "Princess of Swords { http://i.imgur.com/tfJ2Uu8.jpg }",
                "Ace of Disks { http://i.imgur.com/6FszJp0.jpg }",
                "2 of Disks - Change { http://i.imgur.com/TC3Z0dv.jpg }",
                "3 of Disks - Works { http://i.imgur.com/ZRYRFoQ.jpg }",
                "4 of Disks - Power { http://i.imgur.com/pDi6yuu.jpg }",
                "5 of Disks - Worry { http://i.imgur.com/pEtyIqx.jpg }",
                "6 of Disks - Success { http://i.imgur.com/M2HXS5A.jpg }",
                "7 of Disks - Failure { http://i.imgur.com/ApPSuWl.jpg }",
                "8 of Disks - Prudence { http://i.imgur.com/wg2g8gu.jpg }",
                "9 of Disks - Gain { http://i.imgur.com/mEAyRq2.jpg }",
                "10 of Disks - Wealth { http://i.imgur.com/Z3B5V5E.jpg }",
                "Knight of Disks { http://i.imgur.com/iseQPhE.jpg }",
                "Queen of Disks { http://i.imgur.com/NNi2jMu.jpg }",
                "Prince of Disks { http://i.imgur.com/9CQeGof.jpg }",
                "Princess of Disks { http://i.imgur.com/i2lye5C.jpg }"
]


# Album: http://imgur.com/a/0kpnp
RUNES = [   "Fa { http://i.imgur.com/zC7cS7M.png }",
            "Ur { http://i.imgur.com/Sse1tNK.png }",
            "Dorn { http://i.imgur.com/G9WRfPl.png }",
            "Os { http://i.imgur.com/nXWSWCl.png }",
            "Rit { http://i.imgur.com/BK2kpvj.png }",
            "Ka { http://i.imgur.com/X5TeoTh.png }",
            "Hagal { http://i.imgur.com/hmqNO1x.png }",
            "Not { http://i.imgur.com/bUmgnRz.png }",
            "Is { http://i.imgur.com/meNfFda.png }",
            "Ar { http://i.imgur.com/hMG6IFF.png }",
            "Sig { http://i.imgur.com/ogkcrgG.png }",
            "Tyr { http://i.imgur.com/w34JNgD.png }",
            "Bar { http://i.imgur.com/VA3zSqr.png }",
            "Laf { http://i.imgur.com/2Up3N5P.png }",
            "Man { http://i.imgur.com/7XKbcCF.png }",
            "Yr { http://i.imgur.com/QCgTTit.png }",
            "Eh { http://i.imgur.com/bI1APQT.png }",
            "Gibor { http://i.imgur.com/tLHLSyP.png }"
]


MORGAN = [  "TRANSMUTATION THROUGH UNION OF OPPOSITES { http://www.sleepbot.com/morgan/card/morgans.html }",
            "YOUR MISSION IS NOT YET COMPLETE { http://www.sleepbot.com/morgan/card/mission.html }",
            "THERE ARE NO MISTEAKS { http://www.sleepbot.com/morgan/card/misteaks.html }",
            "PASSION { http://www.sleepbot.com/morgan/card/passion.html }",
            "IT IS NOT WHAT YOU DO THAT COUNTS, IT IS WHERE YOUR HEAD IS AT { http://www.sleepbot.com/morgan/card/headisat.html }",
            "GO AHEAD ON { http://www.sleepbot.com/morgan/card/on.html }",
            "DO IT NOW { http://www.sleepbot.com/morgan/card/doitnow.html }",
            "I THINK I'LL MAKE A BUDDHA { http://www.sleepbot.com/morgan/card/buddha.html }",
            "KEEP UP THE GOOD WORK { http://www.sleepbot.com/morgan/card/goodwork.html }",
            "WHO AM I? { http://www.sleepbot.com/morgan/card/whoami.html }",
            "WHATEVER'S RIGHT { http://www.sleepbot.com/morgan/card/right.html }",
            "DO NOT MEDDLE IN THE AFFAIRS OF WIZARDS FOR THEY ARE SUBTLE & QUICK TO ANGER { http://www.sleepbot.com/morgan/card/wizards.html }",
            "THINK ABOUT IT FOR AWHILE { http://www.sleepbot.com/morgan/card/think.html }",
            "I STILL DON'T UNDERSTAND { http://www.sleepbot.com/morgan/card/undrstnd.html }",
            "DON'T WORRY, YOU CAN DO NO WRONG { http://www.sleepbot.com/morgan/card/nowrong.html }",
            "SOMEONE IS LAUGHING AT YOU { http://www.sleepbot.com/morgan/card/laughing.html }",
            "THE ONE MIND IS ROOTLESS AND FOUNDATIONLESS { http://www.sleepbot.com/morgan/card/mind.html }",
            "DEATH/REBIRTH { http://www.sleepbot.com/morgan/card/rebirth.html }",
            "HEAVY { http://www.sleepbot.com/morgan/card/heavy.html }",
            "FREAK { http://www.sleepbot.com/morgan/card/freak.html }",
            "BE CAREFUL GOING AROUND CURVES { http://www.sleepbot.com/morgan/card/curves.html }",
            "SOMEWHERE, THERE IS AN ENERGY LEAK { http://www.sleepbot.com/morgan/card/energy.html }",
            "BALL { http://www.sleepbot.com/morgan/card/ball.html }",
            "THE VIRGIN SUN QUEEN { http://www.sleepbot.com/morgan/card/sunqueen.html }",
            "NO TRIPS WITHOUT A TRIPPER { http://www.sleepbot.com/morgan/card/tripper.html }",
            "TRIP { http://www.sleepbot.com/morgan/card/trip.html }",
            "THE PATH { http://www.sleepbot.com/morgan/card/path.html }",
            "The Blank Card { http://www.sleepbot.com/morgan/card/blank.html }",
            "WHAT ARE YOU FEELING NOW? { http://www.sleepbot.com/morgan/card/feeling.html }",
            "DRINK GOLD { http://www.sleepbot.com/morgan/card/gold.html }",
            "WHAT'S HAPPENING? { http://www.sleepbot.com/morgan/card/happenng.html }",
            "GRASS { http://www.sleepbot.com/morgan/card/grass.html }",
            "AND THERE I WAS ... SURROUNDED { http://www.sleepbot.com/morgan/card/surround.html }",
            "THERE IS NOTHING YOU CAN DO { http://www.sleepbot.com/morgan/card/youcando.html }",
            "AWAKE! { http://www.sleepbot.com/morgan/card/awake.html }",
            "WHO IS WATCHING THE COSMIC DRAMA? { http://www.sleepbot.com/morgan/card/drama.html }",
            "YOU ARE EXPERIENCING AN ILLEGITIMATE FEELING { http://www.sleepbot.com/morgan/card/illegit.html }",
            "MUSHROOM { http://www.sleepbot.com/morgan/card/mushroom.html }",
            "DOWN HOME FUNK { http://www.sleepbot.com/morgan/card/funk.html }",
            "NOBODY HERE BUT US FOLK { http://www.sleepbot.com/morgan/card/usfolk.html }",
            "SLIMY GLOB REIGNS { http://www.sleepbot.com/morgan/card/glob.html }",
            "YESTERDAY'S TRUTH OR WHAT WAS IT I WAS DOING A MINUTE AGO { http://www.sleepbot.com/morgan/card/yestruth.html }",
            "YOUR DOUBT IS YOUR FAITH IF NECESSARY IN YOUR PARTICULAR CASE PERHAPS { http://www.sleepbot.com/morgan/card/doubt.html }",
            "THIS MAY NOT BE A PERFECT CIRCLE BUT IT IS A PERFECT ... WHATEVER IT IS { http://www.sleepbot.com/morgan/card/perfect.html }",
            "BOO!!! { http://www.sleepbot.com/morgan/card/boo.html }",
            "DRUG DRAGGED { http://www.sleepbot.com/morgan/card/dragged.html }",
            "POWER { http://www.sleepbot.com/morgan/card/power.html }",
            "YOU ARE A PAWN { http://www.sleepbot.com/morgan/card/pawn.html }",
            "AS ABOVE, SO BELOW { http://www.sleepbot.com/morgan/card/asabove.html }",
            "MAYA THE FIELD OF THE LORD { http://www.sleepbot.com/morgan/card/maya.html }",
            "THE DREAM { http://www.sleepbot.com/morgan/card/dream.html }",
            "YOU ARE OUR GOD { http://www.sleepbot.com/morgan/card/ourgod.html }",
            "DU WACKY DU { http://www.sleepbot.com/morgan/card/duwacky.html }",
            "HAND { http://www.sleepbot.com/morgan/card/hand.html }",
            "IT'S A DOG EAT DOG FOOD WORLD { http://www.sleepbot.com/morgan/card/dogfood.html }",
            "IGNORE THE PRECEDING { http://www.sleepbot.com/morgan/card/ignore.html }",
            "FAR OUT { http://www.sleepbot.com/morgan/card/farout.html }",
            "ETERNAL BLISS { http://www.sleepbot.com/morgan/card/bliss.html }",
            "STOP { http://www.sleepbot.com/morgan/card/stop.html }",
            "THE UNIVERSE IS NOT UNFOLDING THE WAY IT SHOULD { http://www.sleepbot.com/morgan/card/unfold.html }",
            "DOOR TO THE AKASHIC RECORDS { http://www.sleepbot.com/morgan/card/akashic.html }",
            "THERE IS NO YOU { http://www.sleepbot.com/morgan/card/noyou.html }",
            "FROM HERE ON IT'S NOTHING BUT A DOWNHILL RUN { http://www.sleepbot.com/morgan/card/downhill.html }",
            "AWAIT FURTHER ORDERS { http://www.sleepbot.com/morgan/card/await.html }",
            "The Whirling Golden Wheel { http://www.sleepbot.com/morgan/card/wheel.html }",
            "SPEED { http://www.sleepbot.com/morgan/card/speed.html }",
            "IF THERE IS A JUDGE YOU ARE IT { http://www.sleepbot.com/morgan/card/judge.html }",
            "THERE ARE NO OTHERS { http://www.sleepbot.com/morgan/card/noothers.html }",
            "IN SIGNIFICANT CHANGE { http://www.sleepbot.com/morgan/card/change.html }",
            "WAIT { http://www.sleepbot.com/morgan/card/wait.html }",
            "The Robot { http://www.sleepbot.com/morgan/card/robot.html }",
            "FORGET IT { http://www.sleepbot.com/morgan/card/forgetit.html }",
            "THE WAR HAS REACHED A CRITICAL POINT ... BETWEEN ATLANTIS AND MU { http://www.sleepbot.com/morgan/card/critical.html }",
            "I COME FROM A DIFFERENT PLANET { http://www.sleepbot.com/morgan/card/planet.html }",
            "TOMATO, POTATO, EGGPLANT { http://www.sleepbot.com/morgan/card/eggplant.html }",
            "BABA { http://www.sleepbot.com/morgan/card/baba.html }",
            "O { http://www.sleepbot.com/morgan/card/circle.html }",
            "THIS IS CENTRAL HEADQUARTERS { http://www.sleepbot.com/morgan/card/central.html }",
            "THE VALLEY { http://www.sleepbot.com/morgan/card/valley.html }",
            "DOES CONSCIOUSNESS RING A BELL? { http://www.sleepbot.com/morgan/card/ringbell.html }",
            "MESSAGES MONDAY { http://www.sleepbot.com/morgan/card/monday.html }",
            "LET GEORGE DO IT { http://www.sleepbot.com/morgan/card/george.html }",
            "LOVE { http://www.sleepbot.com/morgan/card/love.html }",
            "PIGS AND FISHES SURROUND YOU { http://www.sleepbot.com/morgan/card/pigfish.html }",
            "TEE HEE HA HA { http://www.sleepbot.com/morgan/card/teehee.html }",
            "TRY TO RELAX { http://www.sleepbot.com/morgan/card/relax.html }",
            "ALWAYS REMEMBER THIS { http://www.sleepbot.com/morgan/card/remember.html }",
            "WORDLESS { http://www.sleepbot.com/morgan/card/wordless.html }"
]